name: habit_rpg
description: RPG gamification for habits and tasks
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI и навигация
  cupertino_icons: ^1.0.6
  
  # Локальное хранение
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Работа с изображениями
  image_picker: ^1.0.4
  cached_network_image: ^3.3.0
  
  # HTTP запросы для API
  dio: ^5.3.2
  
  # Управление состоянием
  provider: ^6.0.5
  
  # Утилиты
  path_provider: ^2.1.1
  path: ^1.8.3
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/