name: habit_rpg
description: "Habit RPG - превратите свои привычки в игру"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter

  # UI и анимации
  cupertino_icons: ^1.0.8
  
  # Управление состоянием
  provider: ^6.1.5
  
  # Локальное хранилище
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.4
  path: ^1.9.0
  
  # Работа с изображениями
  image_picker: ^1.1.2
  cached_network_image: ^3.4.0
  
  # Сеть
  dio: ^5.8.0
  connectivity_plus: ^5.0.2
  
  # Разрешения
  permission_handler: ^11.3.1
  
  # Уникальные ID
  uuid: ^4.5.1
  
  # WebView для Ready Player Me
  webview_flutter: ^4.8.0
  webview_flutter_android: ^3.16.3
  webview_flutter_wkwebview: ^3.14.0
  
  # URL launcher
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2
  
  # Кодогенерация для Hive
  hive_generator: ^2.0.1
  build_runner: ^2.4.9
  json_annotation: ^4.9.0

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic